name: @pluginName@
version: @version@
description: @description@
main: com.github.shatteredsuite.@projectName@.@pluginName@
author: UberPilot
api-version: "1.13"
depend:
  - ShatteredCore
softdepend:
  - Essentials
  - Skript
commands:
  scrolls:
    description: Base command for ShatteredScrolls.
    aliases:
      - scr
      - shatteredscrolls
      - sscr
